### ISSUE TITLE
How long will the program take to run before it is ready for use?

### ISSUE THREAD

**Issue by huynq55-v2** [krukah/robopoker#25]
Currently, I find that the program is taking quite a lot of time to execute. Will you update this repository in the near future with precomputed data?

**Comment by 404raphael** [comment]
It depends on your cpu.  On Windows with 7950x3d it took me ~38m but on macOS with i7-8850H I'm still waiting after 3h.

**Comment by huynq55-v2** [comment]
Is it full deck or short deck?

**Comment by 404raphael** [comment]
Short deck probably, it was a simple cargo run --release from f0f31302d323a0a176685d270f1e3df3d6fcdd25. And had the serialization problem afterwards.
