### ISSUE TITLE
README for variables

### ISSUE THREAD

**Issue by mayanksingh2298** [krukah/robopoker#27]
Hey this looks like some amazing work. 

I'm trying to go through this code with the help of chatgpt, because rust is not my strong unit, but I'm picking it up.

Would love to make some enhancements to this.

Can you help me with a simple readme on how to tune the parameters?
- short deck v/s full deck
- where to set the number of players
- does this use the same algorithm as the original pluribus
- any roadmap to add opponent modelling?
- real time MCTS still in progress? What is the latest on that?
- what is the run time for the specs you mention in README?

**Comment by krukah** [comment]
great to hear, thanks for opening the issue!

- using cargo + `--features shortdeck` will use rust's conditional compilation to basically truncate the deck. grep for `feature = "shortdeck"` to see how it's implemented
- number of players + abstraction parameters + cfr parameters are defined in lib.rs
- there are many algorithms in the original pluribus, so can't give a definitive answer without more specification. but generally: i've tried to stick to the described implementation as much as possible. the literature also doesn't provide source code, and there's some hand-waving with the implementation of certain algorithms (specifically EMD used in kmeans)
- not familiar with opponent modeling -- can you say more / link to any resources about it? seems worth exploring for sure
- haven't broken ground on real time MCTS. we've been doing some analysis on the foundational kmeans abstraction + MCCFR training which i wanna make some optimizations to before moving on to real-time search
- it depends entirely on the parameters you set -- to get up and running, i recommend a shortdeck + 8 clusters for flop & turn + a few million CFR iterations + max_raise = 3 -- this will take around 200 CPUhrs maybe? honestly best way to find out would be to use the progress bar, if you have a TTY terminal available on your machine

**Comment by krukah** [comment]
this is pretty much a passion project i've been working on the side for a few months, originally just to learn Rust but i've seen a lot of interest in the library from people who want to do their own research / build their own products which has been cool. but there's no official roadmap or anything at the moment -- my plan is to probably build some tools to analyze the `street.abstraction` and `blueprint.profile` lookup tables, and also build a simple BlueprintPlayer that you can play against in the CLI, before implementing the game-changing-pluribus-differentiating real-time search feature

**Comment by krukah** [comment]
always welcoming + encouraging contributions though, so happy to brainstorm whatever enhancements you had in mind

**Comment by mayanksingh2298** [comment]
thanks again for your response. Maybe I can finally get in on rust while exploring this project.

Sound like a good motivation
