### ISSUE TITLE
How to use the output files

### ISSUE THREAD

**Issue by hs11346** [krukah/robopoker#28]
I ran the code for a few days, for 2 player full deck. And the pgcopy files that came up seem to be just random characters. How do I use it to access the blueprint strategy?

**Comment by krukah** [comment]
check out postgres documentation (or consult an LLM) on how to upload the binary format into postgres. alternatively, you can alter the code to read it into memory as a BTree (which is effectively what postgres does, just with more indices)

**Comment by krukah** [comment]
but i also may have to revisit the blueprint.profile lifecycle, since i ran it once and got back an empty table. so i think the .save() method isn't working as desired, despite it passing the Profile::persistence test

**Comment by krukah** [comment]
the good thing is, keeping the abstraction files saves you all the hard work and compute. the profile is trained "online" in the sense that it accumulates progress and can be fine tuned over several runs. so just be sure to hold on to the .abstraction.pgcopy files

**Comment by krukah** [comment]
would appreciate a star if you've found the repository interesting so far 😗

**Comment by hs11346** [comment]
Thank you for your quick response! I run the code until I got the turn.abstraction.pgcopy, but unfortunately the code was interrupted. Is there any way to pick up the progress after the turn.abstraction.pgcopy?

**Comment by krukah** [comment]
you can definitely make it work with some source code adjustments, but doesn't have that functionality out of the box
