### ISSUE TITLE
Revert GameNode actions

### ISSUE THREAD

**Issue by krukah** [krukah/robopoker#4]
a node should be able to revert an action to return to a previous state

**Comment by krukah** [comment]
- if you were ::Playing coming from the 'right, you must be ::Playing now
- return

- if you were ::Shoved or ::Folded coming from the 'right, 
- if the provided Action was a ::Shove/::Fold, you must be ::Playing now 
- change status, return
- otherwise, continue 'right

**Comment by zalupakonja666** [comment]
Fix implemented and tested. Changes:

1. Encoder sites routed through 4-tuple with real `game.turn().position()`:
   - `engine/crates/nlhe/src/encoder.rs:70` (root)
   - `engine/crates/nlhe/src/encoder.rs:102` (resume)
2. Worker sites in `--slow` path routed through 4-tuple:
   - `engine/crates/autotrain/src/workers/worker.rs:102` (seed)
   - `engine/crates/autotrain/src/workers/worker.rs:120` (info)
3. API decode/encode now carries position:
   - Added `position: u8` field to `ApiStrategy` DTO (`engine/crates/util/src/dto/response.rs`)
   - `api_strategy_from` in `engine/crates/server/src/analysis/api.rs` emits it
   - `TryFrom<ApiStrategy> for Strategy` at `engine/crates/nlhe/src/strategy.rs:121` consumes it via 4-tuple
4. 3-tuple `impl From<(Path, Abstraction, Path)> for NlheInfo` gated behind `#[cfg(test)]` — production can no longer default-collapse to `position=0`
5. Regression test `seat_distinguishes_otherwise_identical_infosets` — iterates all N seats with identical (subgame, bucket, choices), asserts 6 distinct infoset keys

Verification: `cargo build --workspace --features database` clean (only pre-existing `total_rake` dead-code warning). `cargo test --workspace --features database --lib` — **all tests pass** (123 + 63 + 41 + 59 + 20 + 17 across crates), including the new regression.

Ready for review; not closing yet — will close after PR merges or user confirms.
